import type { Honoree } from './types';

// Research-backed candidate list. Every entry is a real, currently-operating
// organization headquartered or primarily based in Palm Beach County, verified
// against the `source` URL recorded on each record.
//
// `rank` is a stable display index, NOT an ordinal ranking of merit.

export const honorees: Honoree[] = [
  // ─── Capital & Wealth ──────────────────────────────────────────────────────
  {
    rank: 1,
    name: 'Affiliated Managers Group',
    city: 'West Palm Beach',
    category: 'Capital & Wealth',
    description: 'Publicly traded holding company with equity stakes in independent global asset managers.',
    why: 'NYSE-listed multi-affiliate manager overseeing roughly $651 billion in assets, having relocated its headquarters from Massachusetts to West Palm Beach.',
    focus: 'Multi-affiliate asset management',
    founded: '1993',
    source: 'https://en.wikipedia.org/wiki/Affiliated_Managers_Group',
  },
  {
    rank: 2,
    name: 'Sun Capital Partners',
    city: 'Boca Raton',
    category: 'Capital & Wealth',
    description: 'Private equity firm acquiring and operating middle-market companies across industries.',
    why: 'Has acquired more than 540 companies representing over $50 billion in combined revenue since its 1995 founding.',
    focus: 'Leveraged buyout private equity',
    founded: '1995',
    source: 'https://en.wikipedia.org/wiki/Sun_Capital_Partners',
  },
  {
    rank: 3,
    name: 'Comvest Partners',
    city: 'West Palm Beach',
    category: 'Capital & Wealth',
    description: 'Private investment firm providing equity and credit financing to middle-market companies.',
    why: 'Manages roughly $15.7 billion in assets and has deployed over $5.1 billion into the middle market since 2000.',
    focus: 'Private equity and credit',
    founded: '2000',
    source: 'https://fintrx.com/firms/firm/comvest-credit-advisors-llc-311663',
  },
  {
    rank: 4,
    name: 'Onity Group',
    city: 'West Palm Beach',
    category: 'Capital & Wealth',
    description: 'Mortgage servicing and asset management company operating loan platforms nationwide.',
    why: 'NYSE-listed servicer that rebranded from Ocwen Financial in June 2024 while keeping its West Palm Beach headquarters.',
    focus: 'Mortgage servicing',
    founded: '1988',
    source: 'https://en.wikipedia.org/wiki/Onity_Group',
  },
  {
    rank: 5,
    name: 'AE Industrial Partners',
    city: 'Boca Raton',
    category: 'Capital & Wealth',
    description: 'Private equity firm investing in aerospace, defense, space and industrial services companies.',
    why: 'Reported approximately $9.2 billion in assets under management as of December 2025.',
    focus: 'Aerospace and defense PE',
    founded: '1998',
    source: 'https://fintrx.com/firms/firm/ae-industrial-partners-lp-173020',
  },
  {
    rank: 6,
    name: 'Prospect Capital Management',
    city: 'West Palm Beach',
    category: 'Capital & Wealth',
    description: 'Alternative investment manager focused on direct lending, real estate equity and structured credit.',
    why: 'Manages approximately $9.6 billion in assets as of September 2025.',
    focus: 'Private credit and equity',
    founded: '1988',
    source: 'https://www.prospectcap.com/',
  },
  {
    rank: 7,
    name: 'GenSpring Family Offices',
    city: 'Palm Beach Gardens',
    category: 'Capital & Wealth',
    description: 'Multi-family office providing wealth management for ultra-high-net-worth families.',
    why: 'Oversees roughly $25 billion in assets under advisement as a Truist private wealth affiliate.',
    focus: 'Multi-family office',
    founded: '1989',
    source: 'https://www.cbinsights.com/company/genspring-family-offices',
  },
  {
    rank: 8,
    name: 'Gramercy Funds Management',
    city: 'West Palm Beach',
    category: 'Capital & Wealth',
    description: 'Investment manager specializing in emerging-markets debt, credit and special situations.',
    why: 'Manages roughly $6 billion in assets, having grown from a boutique emerging-markets debt shop founded in 1998.',
    focus: 'Emerging markets investing',
    founded: '1998',
    source: 'https://en.wikipedia.org/wiki/Gramercy_Funds_Management',
  },
  {
    rank: 9,
    name: 'Wexford Capital',
    city: 'West Palm Beach',
    category: 'Capital & Wealth',
    description: 'Investment management firm running hedge funds and private equity, including distressed situations.',
    why: 'A multi-strategy manager operating from West Palm Beach since its 1994 founding by Charles Davidson and Joseph Jacobs.',
    focus: 'Hedge fund and private equity',
    founded: '1994',
    source: 'https://altss.com/profile/wexford-capital',
  },
  {
    rank: 10,
    name: '1789 Capital',
    city: 'Palm Beach',
    category: 'Capital & Wealth',
    description: 'Venture capital firm investing in defense, energy and technology companies.',
    why: 'Founded in October 2022, its assets grew roughly seventeen-fold to about $3.5 billion by mid-2026.',
    focus: 'Venture capital',
    founded: '2022',
    source: 'https://en.wikipedia.org/wiki/1789_Capital',
  },
  {
    rank: 11,
    name: 'Chatham Lodging Trust',
    city: 'West Palm Beach',
    category: 'Capital & Wealth',
    description: 'Self-advised REIT investing in upscale extended-stay and premium select-service hotels.',
    why: 'NYSE-listed hospitality REIT headquartered on Lakeview Avenue in West Palm Beach since its 2009 founding.',
    focus: 'Hospitality REIT',
    founded: '2009',
    source: 'https://www.reit.com/investing/reit-directory/chatham-lodging-trust',
  },
  {
    rank: 12,
    name: 'Palm Beach Capital',
    city: 'West Palm Beach',
    category: 'Capital & Wealth',
    description: 'Private equity group financing growth-oriented lower middle-market companies nationwide.',
    why: 'Has invested continuously from its West Palm Beach base since 2001, one of the county’s longest-tenured private equity shops.',
    focus: 'Lower middle-market PE',
    founded: '2001',
    source: 'https://www.pbcap.com/',
  },
  {
    rank: 13,
    name: 'Paulson & Co.',
    city: 'Palm Beach',
    category: 'Capital & Wealth',
    description: 'Hedge fund and family investment office led by investor John Paulson.',
    why: 'Completed a headquarters build-out at the One Flagler tower, among the highest-profile finance relocations to Palm Beach.',
    focus: 'Hedge fund and family office',
    founded: '1994',
    source: 'https://www.brgintl.com/billionaire-john-paulson-establishes-first-office-in-south-florida/',
  },

  // ─── Real Estate & Development ─────────────────────────────────────────────
  {
    rank: 14,
    name: 'Related Ross',
    city: 'West Palm Beach',
    category: 'Real Estate & Development',
    description: 'Developer and Class A office landlord reshaping downtown West Palm Beach.',
    why: 'The city’s largest developer, owning nearly 3 million square feet of commercial space and investing roughly $10 billion across 8 million square feet.',
    focus: 'Downtown office and mixed-use',
    founded: '2024',
    source: 'https://www.relatedross.com/',
  },
  {
    rank: 15,
    name: 'The Kolter Group',
    city: 'Delray Beach',
    category: 'Real Estate & Development',
    description: 'Diversified developer building condominiums, homes, apartments and hotels across the Southeast.',
    why: 'Has invested in projects with expected value exceeding $30 billion since its 1997 founding.',
    focus: 'Diversified development',
    founded: '1997',
    source: 'https://www.kolter.com/about-us/',
  },
  {
    rank: 16,
    name: 'CP Group',
    city: 'Boca Raton',
    category: 'Real Estate & Development',
    description: 'Commercial real estate investment firm acquiring and repositioning office and mixed-use properties.',
    why: 'Florida’s largest office landlord, having repositioned over 170 properties totalling more than 64 million square feet.',
    focus: 'Office property investment',
    founded: '1986',
    source: 'https://cpgcre.com/news/cre-investment-firm-crocker-partners-rebrands-cp-group/',
  },
  {
    rank: 17,
    name: 'Menin Development',
    city: 'Delray Beach',
    category: 'Real Estate & Development',
    description: 'Privately owned developer of commercial, retail and hospitality real estate.',
    why: 'Owns most of Atlantic Avenue’s key retail blocks and has acquired more than $1 billion in property.',
    focus: 'Retail district development',
    founded: '1985',
    source: 'https://menin.com/',
  },
  {
    rank: 18,
    name: 'Frisbie Group',
    city: 'Palm Beach',
    category: 'Real Estate & Development',
    description: 'Family-run real estate investment and development firm active on the island and downtown.',
    why: 'Developed the 1 and 101 North Clematis mixed-use complex, a landmark of downtown West Palm Beach’s Clematis corridor.',
    focus: 'Luxury real estate investment',
    founded: '1996',
    source: 'https://therealdeal.com/miami/2025/10/30/palm-beach-development-family-with-billions-in-the-pipeline/',
  },
  {
    rank: 19,
    name: 'NAI/Merin Hunter Codman',
    city: 'West Palm Beach',
    category: 'Real Estate & Development',
    description: 'Full-service commercial brokerage, property management and construction management firm.',
    why: 'The largest privately owned commercial real estate firm headquartered in Palm Beach County.',
    focus: 'Commercial brokerage',
    founded: '1992',
    source: 'https://www.mhcreal.com/about-us/',
  },
  {
    rank: 20,
    name: 'Illustrated Properties Real Estate',
    city: 'Palm Beach Gardens',
    category: 'Real Estate & Development',
    description: 'Independent residential brokerage serving Palm Beach and the Treasure Coast.',
    why: 'The largest family-owned brokerage network in Palm Beach County, with over $6 billion in annual sales volume.',
    focus: 'Residential brokerage',
    founded: '1975',
    source: 'https://www.ipre.com/our-story/',
  },
  {
    rank: 21,
    name: 'Ram Realty Advisors',
    city: 'Palm Beach Gardens',
    category: 'Real Estate & Development',
    description: 'Investment and development firm targeting Southeast residential and mixed-use projects.',
    why: 'A registered investment adviser managing roughly $2.1 billion in assets from its PGA Boulevard headquarters.',
    focus: 'Real estate investment management',
    founded: '1978',
    source: 'https://fintrx.com/firms/firm/ram-realty-advisors-llc-160238',
  },
  {
    rank: 22,
    name: 'Premier Estate Properties',
    city: 'Boca Raton',
    category: 'Real Estate & Development',
    description: 'Boutique brokerage exclusively representing properties priced above one million dollars.',
    why: 'Generated $4.9 billion in sales and listings in a single twelve-month period with fewer than 42 agents.',
    focus: 'Ultra-luxury brokerage',
    founded: '1993',
    source: 'https://www.luxuryrealestate.com/profiles/5182',
  },
  {
    rank: 23,
    name: 'Waterfront Properties & Club Communities',
    city: 'Jupiter',
    category: 'Real Estate & Development',
    description: 'Luxury brokerage specializing in waterfront homes and private club communities.',
    why: 'Founded in 1988 by Rob Thomson and among the largest luxury real estate firms in South Florida.',
    focus: 'Waterfront luxury brokerage',
    founded: '1988',
    source: 'https://www.waterfront-properties.com/about.php',
  },
  {
    rank: 24,
    name: 'Butters Construction & Development',
    city: 'Boca Raton',
    category: 'Real Estate & Development',
    description: 'Family-owned commercial developer and general contractor for office, industrial and retail projects.',
    why: 'Manages roughly 3 million square feet of space and is a seven-time NAIOP Developer of the Year honoree.',
    focus: 'Commercial construction',
    founded: '1971',
    source: 'https://butters.com/about-us/',
  },
  {
    rank: 25,
    name: 'Brand Atlantic Real Estate Partners',
    city: 'West Palm Beach',
    category: 'Real Estate & Development',
    description: 'Investment company acquiring, developing and repositioning urban properties.',
    why: 'Founded in 2021 by a former Related Companies executive and has since developed four downtown West Palm Beach properties.',
    focus: 'Urban office redevelopment',
    founded: '2021',
    source: 'https://www.brandatlantic.com/',
  },
  {
    rank: 26,
    name: 'REG Architects',
    city: 'West Palm Beach',
    category: 'Real Estate & Development',
    description: 'Architecture, interiors and planning firm known for historic preservation and urban design.',
    why: 'Designed the landmark Harriett Himmel Theater anchoring CityPlace and Rosemary Square in downtown West Palm Beach.',
    focus: 'Architecture and preservation',
    founded: '1988',
    source: 'https://www.regarchitects.com/',
  },
  {
    rank: 27,
    name: 'Peacock + Lewis Architects and Planners',
    city: 'North Palm Beach',
    category: 'Real Estate & Development',
    description: 'Master planning, architecture and interior design firm specializing in hospitality and club amenities.',
    why: 'Tracing to 1961 on Palm Beach island, it has designed more than 20 Platinum-rated golf and country clubs nationally.',
    focus: 'Club and hospitality architecture',
    founded: '1961',
    source: 'https://peacockandlewis.com/about/',
  },

  // ─── Luxury, Hospitality & Lifestyle ───────────────────────────────────────
  {
    rank: 28,
    name: 'The Breakers Palm Beach',
    city: 'Palm Beach',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Oceanfront luxury resort set on 140 acres in the heart of Palm Beach.',
    why: 'Opened by Henry Flagler in 1896 and rebuilt in 1926, its 569 rooms make it the defining institution of Palm Beach hospitality.',
    focus: 'Historic luxury resort',
    founded: '1896',
    source: 'https://www.thebreakers.com/about/look-back/',
  },
  {
    rank: 29,
    name: 'The Boca Raton',
    city: 'Boca Raton',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Waterfront luxury resort complex spanning multiple hotels, clubs and a private beach.',
    why: 'Opened in 1926 as Addison Mizner’s Cloister Inn and now spans 337 acres with 1,047 rooms.',
    focus: 'Historic luxury resort',
    founded: '1926',
    source: 'https://en.wikipedia.org/wiki/The_Boca_Raton_Resort',
  },
  {
    rank: 30,
    name: 'Eau Palm Beach Resort & Spa',
    city: 'Manalapan',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Oceanfront luxury resort with a large full-service destination spa.',
    why: 'Held Forbes Five-Star status for nine consecutive years and AAA Five Diamond rating before its 2024 sale to Larry Ellison.',
    focus: 'Five-star resort and spa',
    founded: '1990',
    source: 'https://www.forbes.com/sites/suzannerowankelleher/2024/08/13/larry-ellison-palm-beach-resort-mar-a-lago/',
  },
  {
    rank: 31,
    name: 'The Colony Hotel Palm Beach',
    city: 'Palm Beach',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Landmark pink boutique hotel and social hub steps from Worth Avenue.',
    why: 'Opened in 1947, designated a local historic landmark, and family-owned since 1970.',
    focus: 'Boutique historic hotel',
    founded: '1947',
    source: 'https://en.wikipedia.org/wiki/The_Colony_Hotel',
  },
  {
    rank: 32,
    name: 'Four Seasons Resort Palm Beach',
    city: 'Palm Beach',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Oceanfront luxury resort with 207 rooms and suites on the island’s south end.',
    why: 'Opened in 1989 as one of the island’s few purpose-built modern luxury resorts, later redesigned by Martin Brudnizki.',
    focus: 'Luxury oceanfront resort',
    founded: '1989',
    source: 'https://press.fourseasons.com/palmbeach/hotel-facts/',
  },
  {
    rank: 33,
    name: 'Everglades Club',
    city: 'Palm Beach',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Private social and golf club on Worth Avenue designed by Addison Mizner.',
    why: 'Opened in 1919 as Mizner’s first Palm Beach commission, launching the Mediterranean Revival style that defines the island.',
    focus: 'Private social club',
    founded: '1919',
    source: 'https://en.wikipedia.org/wiki/Everglades_Club',
  },
  {
    rank: 34,
    name: 'Sailfish Club of Florida',
    city: 'Palm Beach',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Private waterfront social club with sailing, fishing and boating facilities.',
    why: 'Organized in 1914, it is the oldest continuously operating private club in the Town of Palm Beach.',
    focus: 'Private yacht club',
    founded: '1914',
    source: 'https://www.sailfishclub.com/about',
  },
  {
    rank: 35,
    name: 'The Bear’s Club',
    city: 'Jupiter',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Ultra-private golf club founded by Jack Nicklaus with a 64,000-square-foot clubhouse.',
    why: 'Founded in 1999 by Jack Nicklaus, its capped membership has drawn many of golf’s leading professionals to Jupiter.',
    focus: 'Private golf club',
    founded: '1999',
    source: 'https://linksmagazine.com/jack-nicklaus-and-the-bears-club/',
  },
  {
    rank: 36,
    name: 'PGA National Resort',
    city: 'Palm Beach Gardens',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Championship golf resort with five 18-hole courses, a spa and tournament venue.',
    why: 'Hosted the 1983 Ryder Cup and 1987 PGA Championship, and completed a $100 million renovation in 2024.',
    focus: 'Championship golf resort',
    founded: '1980',
    source: 'https://en.wikipedia.org/wiki/PGA_National_Resort',
  },
  {
    rank: 37,
    name: 'Wellington International',
    city: 'Wellington',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Equestrian venue hosting the world’s largest annual show-jumping festival across a 13-week season.',
    why: 'Its Winter Equestrian Festival generated an estimated $536.2 million in economic impact in 2025, outpacing every other regional sporting event.',
    focus: 'Equestrian sport venue',
    founded: '1978',
    source: 'https://www.wellingtoninternational.com/palm-beach-countys-winter-equestrian-festival-outpaces-major-sports-events-with-536-2m-economic-impact/',
  },
  {
    rank: 38,
    name: 'Rybovich',
    city: 'West Palm Beach',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Superyacht marina and refit facility on the Intracoastal Waterway.',
    why: 'Rooted in a 1919 boatbuilding shop, its 85-slip marina services megayachts up to 328 feet.',
    focus: 'Superyacht marina and refit',
    founded: '1919',
    source: 'https://www.michaelrybovichandsons.com/about-us/history/',
  },
  {
    rank: 39,
    name: 'Lilly Pulitzer',
    city: 'Palm Beach',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Resort-wear fashion brand known for its vivid signature prints.',
    why: 'Founded on Via Mizner in 1959, early patronage by Jackie Kennedy turned it into a national symbol of Palm Beach style.',
    focus: 'Resort fashion brand',
    founded: '1959',
    source: 'https://en.wikipedia.org/wiki/Lilly_Pulitzer',
  },
  {
    rank: 40,
    name: 'Greenleaf & Crosby',
    city: 'Palm Beach',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Fine jewelry and luxury watch retailer anchoring Worth Avenue.',
    why: 'Opened its Worth Avenue flagship in 1933, the longest tenure of any jeweler in Palm Beach.',
    focus: 'Luxury jewelry retail',
    founded: '1868',
    source: 'https://greenleafcrosby.com/pages/history',
  },
  {
    rank: 41,
    name: 'Buccan',
    city: 'Palm Beach',
    category: 'Luxury, Hospitality & Lifestyle',
    description: 'Chef-driven restaurant group including Buccan, Imoto and Grato.',
    why: 'Opened in 2011 and credited with modernizing Palm Beach dining; chef Clay Conley has earned five James Beard nominations.',
    focus: 'Fine dining group',
    founded: '2011',
    source: 'https://www.buccanpalmbeach.com/the-chef',
  },

  // ─── Professional Power Centers ────────────────────────────────────────────
  {
    rank: 42,
    name: 'NextEra Energy',
    city: 'Juno Beach',
    category: 'Professional Power Centers',
    description: 'Parent company of Florida Power & Light and a leading clean-energy generator.',
    why: 'A Fortune 500 company headquartered in Juno Beach with roughly 16,700 employees, the county’s largest public company by far.',
    focus: 'Energy utility holding company',
    founded: '1984',
    source: 'https://en.wikipedia.org/wiki/NextEra_Energy',
  },
  {
    rank: 43,
    name: 'The ODP Corporation',
    city: 'Boca Raton',
    category: 'Professional Power Centers',
    description: 'Global office products and business services retailer operating Office Depot and OfficeMax.',
    why: 'Publicly traded on NASDAQ with a 625,000-square-foot global headquarters campus in Boca Raton.',
    focus: 'Office products retail',
    founded: '1986',
    source: 'https://investor.officedepot.com/news-releases/news-release-details/office-depot-breaks-ground-new-global-headquarters-boca-raton',
  },
  {
    rank: 44,
    name: 'ADT Inc.',
    city: 'Boca Raton',
    category: 'Professional Power Centers',
    description: 'Leading provider of residential and business security, alarm monitoring and smart-home systems.',
    why: 'NYSE-listed since 2018 and headquartered on West Yamato Road, reporting $4.90 billion in 2024 revenue.',
    focus: 'Security and monitoring',
    founded: '1874',
    source: 'https://en.wikipedia.org/wiki/ADT_Inc.',
  },
  {
    rank: 45,
    name: 'SBA Communications',
    city: 'Boca Raton',
    category: 'Professional Power Centers',
    description: 'Owner and operator of wireless communications towers across the Americas and Africa.',
    why: 'A NASDAQ-listed S&P 500 member headquartered on Congress Avenue since its 1989 founding.',
    focus: 'Wireless tower infrastructure',
    founded: '1989',
    source: 'https://sbasite.com/',
  },
  {
    rank: 46,
    name: 'The GEO Group',
    city: 'Boca Raton',
    category: 'Professional Power Centers',
    description: 'Publicly traded operator of correctional, detention and mental-health facilities worldwide.',
    why: 'NYSE-listed with an estimated 18,000 employees, headquartered on Technology Way in Boca Raton.',
    focus: 'Corrections and detention',
    founded: '1984',
    source: 'https://www.ibisworld.com/united-states/company/the-geo-group-inc/9791/',
  },
  {
    rank: 47,
    name: 'Cheney Brothers',
    city: 'Riviera Beach',
    category: 'Professional Power Centers',
    description: 'Broadline food service distributor supplying restaurants and institutions across the Southeast.',
    why: 'Family-founded in 1925 and employing roughly 3,300 people before its 2024 acquisition by Performance Food Group.',
    focus: 'Food service distribution',
    founded: '1925',
    source: 'https://www.cheneybrothers.com/',
  },
  {
    rank: 48,
    name: 'Florida Crystals Corporation',
    city: 'West Palm Beach',
    category: 'Professional Power Centers',
    description: 'Vertically integrated sugarcane and rice grower, miller, refiner and renewable-energy operator.',
    why: 'Headquartered on Clematis Street, it is one of the largest agricultural landholders and employers in the county.',
    focus: 'Agribusiness',
    founded: '1960',
    source: 'https://floridacrystals.com/careers',
  },
  {
    rank: 49,
    name: 'NCCI',
    city: 'Boca Raton',
    category: 'Professional Power Centers',
    description: 'National organization managing workers’ compensation insurance data, rates and research.',
    why: 'Headquartered in Boca Raton with more than 900 employees serving the workers’ compensation industry nationwide.',
    focus: 'Insurance data authority',
    founded: '1923',
    source: 'https://www.ncci.com/pages/contactus.aspx',
  },
  {
    rank: 50,
    name: 'Gunster',
    city: 'West Palm Beach',
    category: 'Professional Power Centers',
    description: 'Full-service Florida law firm serving business, real estate and private-wealth clients statewide.',
    why: 'More than 330 attorneys and consultants firmwide, with its principal office at Phillips Point on South Flagler Drive.',
    focus: 'Business law',
    founded: '1925',
    source: 'https://www.gunster.com/contact/west-palm-beach',
  },
  {
    rank: 51,
    name: 'Jones Foster',
    city: 'West Palm Beach',
    category: 'Professional Power Centers',
    description: 'Commercial and private-client law firm handling business, real estate, litigation and estate matters.',
    why: 'Traces its roots to 1924, making it one of Florida’s oldest continuously operating law firms.',
    focus: 'Private-client law',
    founded: '1924',
    source: 'https://jonesfoster.com/our-firm/our-first-100-years',
  },
  {
    rank: 52,
    name: 'Ciklin Lubitz',
    city: 'West Palm Beach',
    category: 'Professional Power Centers',
    description: 'Litigation and business law firm handling construction, real estate and family law matters.',
    why: 'Founded in Palm Beach County in 1985 and ranked a Tier 1 Best Law Firm by U.S. News in three local practice areas.',
    focus: 'Litigation and construction law',
    founded: '1985',
    source: 'https://profiles.superlawyers.com/florida/west-palm-beach/lawfirm/ciklin-lubitz/626330cc-a75a-4698-95e0-520c028c71d0.html',
  },
  {
    rank: 53,
    name: 'WGI, Inc.',
    city: 'West Palm Beach',
    category: 'Professional Power Centers',
    description: 'Multidisciplinary civil engineering, surveying, transportation and landscape architecture firm.',
    why: 'Family-owned engineering firm founded in 1972 that has grown to compete for major infrastructure projects statewide.',
    focus: 'Civil engineering',
    founded: '1972',
    source: 'https://wginc.com/family-owned-wgi-competes-with-bigger-firms-lands-major-projects/',
  },

  // ─── Healthcare & Longevity ────────────────────────────────────────────────
  {
    rank: 54,
    name: 'HCA Florida JFK Hospital',
    city: 'Atlantis',
    category: 'Healthcare & Longevity',
    description: 'Acute care hospital and teaching facility operated by HCA Healthcare.',
    why: 'A 486-bed hospital founded in 1966 employing about 2,200 staff and serving as a University of Miami-affiliated teaching site.',
    focus: 'Acute and teaching hospital',
    founded: '1966',
    source: 'https://en.wikipedia.org/wiki/JFK_Medical_Center_(Atlantis,_Florida)',
  },
  {
    rank: 55,
    name: 'Boca Raton Regional Hospital',
    city: 'Boca Raton',
    category: 'Healthcare & Longevity',
    description: 'Not-for-profit acute care hospital serving southern Palm Beach County.',
    why: 'A 400-bed hospital that became a full member of Baptist Health South Florida in 2019.',
    focus: 'Acute care hospital',
    founded: '1967',
    source: 'https://en.wikipedia.org/wiki/Boca_Raton_Regional_Hospital',
  },
  {
    rank: 56,
    name: 'St. Mary’s Medical Center',
    city: 'West Palm Beach',
    category: 'Healthcare & Longevity',
    description: 'Acute care hospital housing the region’s only dedicated children’s hospital.',
    why: 'A 413-bed hospital that invested $11 million expanding its pediatric ICU and $7 million expanding its pediatric emergency room.',
    focus: 'Pediatric and acute care',
    founded: '1938',
    source: 'https://southfloridahospitalnews.com/st-marys-medical-center-invests-in-major-facility-upgrades-to-meet-growing-community-needs/',
  },
  {
    rank: 57,
    name: 'Delray Medical Center',
    city: 'Delray Beach',
    category: 'Healthcare & Longevity',
    description: 'Acute care hospital and Level I trauma center on a 30-acre campus.',
    why: 'One of only two Level I trauma centers in Palm Beach County, treating over 2,000 trauma patients annually.',
    focus: 'Trauma and acute care',
    founded: '1982',
    source: 'https://www.delraymedicalctr.com/docs/librariesproviderdelray/default-document-library/del-43624-update-fact-sheet_cr-0-hr.pdf',
  },
  {
    rank: 58,
    name: 'Jupiter Medical Center',
    city: 'Jupiter',
    category: 'Healthcare & Longevity',
    description: 'Independent, not-for-profit regional medical center serving northern Palm Beach County.',
    why: 'A 327-bed hospital and the first in the Palm Beach and Treasure Coast region to earn a five-star CMS quality rating.',
    focus: 'Regional acute care',
    founded: '1979',
    source: 'https://www.jupitermed.com/news/2019/march/jupiter-medical-center-first-in-region-to-earn-f/',
  },
  {
    rank: 59,
    name: 'Bethesda Hospital East',
    city: 'Boynton Beach',
    category: 'Healthcare & Longevity',
    description: 'Not-for-profit community hospital operating under Baptist Health South Florida.',
    why: 'A 401-bed hospital with a Level III NICU and specialty cancer, cardiac and women’s health programs.',
    focus: 'Community hospital',
    founded: '1959',
    source: 'https://baptisthealth.net/locations/hospitals/bethesda-hospital-east',
  },
  {
    rank: 60,
    name: 'Good Samaritan Medical Center',
    city: 'West Palm Beach',
    category: 'Healthcare & Longevity',
    description: 'Downtown waterfront hospital undergoing a major redevelopment.',
    why: 'A 333-bed hospital being rebuilt as a new high-tech facility within a mixed-use downtown West Palm Beach project.',
    focus: 'Acute care hospital',
    founded: '1920',
    source: 'https://www.palmbeachhealthnetwork.com/news/newsroom/2026/02/20/new-good-samaritan-hospital-with-luxury-housing-and-retail-planned-in-west-palm-beach',
  },
  {
    rank: 61,
    name: 'Health Care District of Palm Beach County',
    city: 'West Palm Beach',
    category: 'Healthcare & Longevity',
    description: 'Voter-established public health system funding trauma, emergency and rural hospital care.',
    why: 'Operates the 70-bed Lakeside Medical Center in Belle Glade and underwrites the county’s trauma and EMS network.',
    focus: 'Public health system',
    founded: '1988',
    source: 'https://www.healthleadersmedia.com/strategy/lakeside-medical-center-opens-palm-beach-county-fl',
  },
  {
    rank: 62,
    name: 'Herbert Wertheim UF Scripps Institute',
    city: 'Jupiter',
    category: 'Healthcare & Longevity',
    description: 'Biomedical research institute for innovation and technology, formerly Scripps Research Florida.',
    why: 'A three-building, 30-acre campus opened in 2009 and fully integrated into the University of Florida’s academic health center in 2022.',
    focus: 'Biomedical research',
    founded: '2009',
    source: 'https://wertheim.scripps.ufl.edu/2022/04/01/uf-scripps-florida-complete-integration-to-create-science-research-powerhouse/',
  },
  {
    rank: 63,
    name: 'Max Planck Florida Institute for Neuroscience',
    city: 'Jupiter',
    category: 'Healthcare & Longevity',
    description: 'Neuroscience research institute located on Florida Atlantic University’s Jupiter campus.',
    why: 'The Max Planck Society’s first and only institute in North America, in a 100,000-square-foot facility opened in 2010.',
    focus: 'Neuroscience research',
    founded: '2010',
    source: 'https://en.wikipedia.org/wiki/Max_Planck_Florida_Institute_for_Neuroscience',
  },
  {
    rank: 64,
    name: 'FAU Charles E. Schmidt College of Medicine',
    city: 'Boca Raton',
    category: 'Healthcare & Longevity',
    description: 'Florida Atlantic University’s medical school offering MD, PhD and biomedical science degrees.',
    why: 'Founded in 2010 as the 134th medical school in the United States; its 2026 class of 79 graduates was its largest ever.',
    focus: 'Medical education',
    founded: '2010',
    source: 'https://en.wikipedia.org/wiki/Charles_E._Schmidt_College_of_Medicine',
  },
  {
    rank: 65,
    name: 'MDVIP',
    city: 'Boca Raton',
    category: 'Healthcare & Longevity',
    description: 'National concierge and preventive-medicine physician network.',
    why: 'Founded in 2000 by two Boca Raton doctors and now serving over 430,000 members through more than 1,400 affiliated physicians.',
    focus: 'Concierge medicine network',
    founded: '2000',
    source: 'https://www.mdvip.com/about-mdvip/press-room/mdvip-celebrates-its-momentum-100-consecutive-quarters-growth-milestone-and-new-boca-raton-hq',
  },
  {
    rank: 66,
    name: 'ZimVie',
    city: 'Palm Beach Gardens',
    category: 'Healthcare & Longevity',
    description: 'Global dental implant and life-sciences company, formerly known as Biomet 3i.',
    why: 'Headquartered in Palm Beach Gardens with roots there spanning nearly 40 years and over 600 local employees.',
    focus: 'Dental implants and medtech',
    founded: '1987',
    source: 'https://bdb.org/industries/life-sciences-healthcare/',
  },

  // ─── Media, Events & Influence ─────────────────────────────────────────────
  {
    rank: 67,
    name: 'The Palm Beach Post',
    city: 'West Palm Beach',
    category: 'Media, Events & Influence',
    description: 'Daily regional newspaper covering Palm Beach County and the Treasure Coast.',
    why: 'Published daily since 1916, with average print circulation of 17,400 plus nearly 4,900 digital subscribers.',
    focus: 'Daily newspaper',
    founded: '1916',
    source: 'https://en.wikipedia.org/wiki/The_Palm_Beach_Post',
  },
  {
    rank: 68,
    name: 'Palm Beach Daily News',
    city: 'Palm Beach',
    category: 'Media, Events & Influence',
    description: 'Society and government newspaper covering the Town of Palm Beach, known as the Shiny Sheet.',
    why: 'Founded in 1897, it is the island’s paper of record and the definitive chronicle of Palm Beach society.',
    focus: 'Society newspaper',
    founded: '1897',
    source: 'https://en.wikipedia.org/wiki/Palm_Beach_Daily_News',
  },
  {
    rank: 69,
    name: 'Palm Beach Illustrated',
    city: 'West Palm Beach',
    category: 'Media, Events & Influence',
    description: 'Glossy monthly lifestyle and society magazine covering Palm Beach County.',
    why: 'Debuted in 1952 and published eleven times a year, the region’s longest-running luxury lifestyle title.',
    focus: 'Lifestyle magazine',
    founded: '1952',
    source: 'https://www.palmbeachillustrated.com/about-us/',
  },
  {
    rank: 70,
    name: 'WPTV NewsChannel 5',
    city: 'West Palm Beach',
    category: 'Media, Events & Influence',
    description: 'NBC-affiliated television station owned by the E.W. Scripps Company.',
    why: 'On air since 1954 and repeatedly cited as one of Florida’s top-rated television news stations.',
    focus: 'Television news',
    founded: '1954',
    source: 'https://en.wikipedia.org/wiki/WPTV-TV',
  },
  {
    rank: 71,
    name: 'WPEC CBS12',
    city: 'West Palm Beach',
    category: 'Media, Events & Influence',
    description: 'CBS-affiliated television station owned by Sinclair Broadcast Group.',
    why: 'Broadcasting since 1955, it is among the market’s oldest continuously operating television stations.',
    focus: 'Television news',
    founded: '1955',
    source: 'https://en.wikipedia.org/wiki/WPEC',
  },
  {
    rank: 72,
    name: 'WPBF 25',
    city: 'Palm Beach Gardens',
    category: 'Media, Events & Influence',
    description: 'ABC-affiliated television station owned by Hearst Television.',
    why: 'Launched on January 1, 1989 and made industry history as the first station to pay a network for its affiliation.',
    focus: 'Television news',
    founded: '1989',
    source: 'https://en.wikipedia.org/wiki/WPBF',
  },
  {
    rank: 73,
    name: 'Palm Beach International Boat Show',
    city: 'West Palm Beach',
    category: 'Media, Events & Influence',
    description: 'Annual luxury yacht and marine industry show staged along Flagler Drive.',
    why: 'Running since 1982, recent editions have drawn more than 55,000 attendees and anchor the region’s marine economy.',
    focus: 'Marine trade show',
    founded: '1982',
    source: 'https://www.pbboatshow.com/en/attend/show_overview.html',
  },
  {
    rank: 74,
    name: 'South Florida Fair',
    city: 'West Palm Beach',
    category: 'Media, Events & Influence',
    description: 'Annual regional fair held each January on a 100-acre fairgrounds.',
    why: 'Founded in 1912 as the Palm Beach County Fair, it now draws close to 500,000 attendees each year.',
    focus: 'Annual fair',
    founded: '1912',
    source: 'https://en.wikipedia.org/wiki/South_Florida_Fair',
  },
  {
    rank: 75,
    name: 'Roger Dean Chevrolet Stadium',
    city: 'Jupiter',
    category: 'Media, Events & Influence',
    description: 'Spring training ballpark for the Miami Marlins and St. Louis Cardinals.',
    why: 'Opened in 1998 with 6,871 seats and is the only stadium in the country hosting four minor league teams.',
    focus: 'Spring training venue',
    founded: '1998',
    source: 'https://en.wikipedia.org/wiki/Roger_Dean_Stadium',
  },
  {
    rank: 76,
    name: 'CACTI Park of the Palm Beaches',
    city: 'West Palm Beach',
    category: 'Media, Events & Influence',
    description: 'Spring training ballpark shared by the Houston Astros and Washington Nationals.',
    why: 'Opened in 2017, returning two Major League franchises and their spring tourism economy to Palm Beach County.',
    focus: 'Spring training venue',
    founded: '2017',
    source: 'https://en.wikipedia.org/wiki/Cacti_Park_of_the_Palm_Beaches',
  },
  {
    rank: 77,
    name: 'Delray Beach Open',
    city: 'Delray Beach',
    category: 'Media, Events & Influence',
    description: 'ATP Tour professional men’s tennis tournament at the Delray Beach Tennis Center.',
    why: 'Set an all-time attendance record of more than 65,000 fans in 2024, the county’s marquee professional tennis event.',
    focus: 'ATP tennis tournament',
    founded: '1993',
    source: 'https://floridatennis.com/blogs/news/delray-beach-open-record-attendance-in-2024-leads-to-earlier-ticket-sales',
  },
  {
    rank: 78,
    name: 'Palm Beach Modern + Contemporary',
    city: 'West Palm Beach',
    category: 'Media, Events & Influence',
    description: 'International modern and contemporary art fair presented by Art Miami.',
    why: 'Reached its ninth edition in 2026, drawing international galleries to the Convention Center at the height of season.',
    focus: 'Art fair',
    founded: '2017',
    source: 'https://news.artnet.com/art-world/palm-beach-modern-and-contemporary-2755835',
  },

  // ─── Philanthropy & Civic Institutions ─────────────────────────────────────
  {
    rank: 79,
    name: 'Norton Museum of Art',
    city: 'West Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Encyclopedic art museum holding European, American, Chinese and contemporary collections.',
    why: 'Founded in 1941 by Ralph and Elizabeth Norton, it holds more than 8,200 works and anchors the county’s cultural life.',
    focus: 'Art museum',
    founded: '1941',
    source: 'https://www.norton.org/about/history',
  },
  {
    rank: 80,
    name: 'Raymond F. Kravis Center for the Performing Arts',
    city: 'West Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Multi-venue performing arts center hosting Broadway tours, opera, ballet and concerts.',
    why: 'Opened debt-free in 1992 after a $55 million donor-funded campaign, with a 2,195-seat main concert hall.',
    focus: 'Performing arts center',
    founded: '1992',
    source: 'https://www.kravis.org/about-us/history/',
  },
  {
    rank: 81,
    name: 'Flagler Museum',
    city: 'Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Historic house museum in Whitehall, Henry Flagler’s 1902 Gilded Age mansion.',
    why: 'Whitehall is a National Historic Landmark, opened to the public in 1960, preserving the origin story of Palm Beach itself.',
    focus: 'Historic house museum',
    founded: '1960',
    source: 'https://en.wikipedia.org/wiki/Whitehall_(Henry_M._Flagler_House)',
  },
  {
    rank: 82,
    name: 'The Society of the Four Arts',
    city: 'Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Cultural center presenting art, music, drama and literature programming plus public gardens.',
    why: 'Founded in 1936, it remains the island’s central cultural institution, with galleries, a concert hall and sculpture gardens.',
    focus: 'Cultural arts center',
    founded: '1936',
    source: 'https://en.wikipedia.org/wiki/Society_of_the_Four_Arts',
  },
  {
    rank: 83,
    name: 'Boca Raton Museum of Art',
    city: 'Boca Raton',
    category: 'Philanthropy & Civic Institutions',
    description: 'Modern and contemporary art museum with photography, sculpture and Pre-Columbian holdings.',
    why: 'Traces to a 1950 artists’ guild and holds more than 180 Pre-Columbian works alongside its modern collection.',
    focus: 'Contemporary art museum',
    founded: '1950',
    source: 'https://en.wikipedia.org/wiki/Boca_Raton_Museum_of_Art',
  },
  {
    rank: 84,
    name: 'Morikami Museum and Japanese Gardens',
    city: 'Delray Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Museum and garden complex preserving Japanese culture and the Yamato colony legacy.',
    why: 'Opened in 1977 on land gifted by George Morikami, a survivor of the early-1900s Yamato agricultural colony.',
    focus: 'Cultural museum and gardens',
    founded: '1977',
    source: 'https://en.wikipedia.org/wiki/Morikami_Museum_and_Japanese_Gardens',
  },
  {
    rank: 85,
    name: 'Florida Atlantic University',
    city: 'Boca Raton',
    category: 'Philanthropy & Civic Institutions',
    description: 'Public research university and the county’s largest higher education institution.',
    why: 'Opened in 1964 with 867 students and now enrolls more than 30,000 across seven campuses.',
    focus: 'Public research university',
    founded: '1964',
    source: 'https://en.wikipedia.org/wiki/Florida_Atlantic_University',
  },
  {
    rank: 86,
    name: 'Palm Beach Atlantic University',
    city: 'West Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Private Christian liberal arts university in downtown West Palm Beach.',
    why: 'Founded in 1968, it enrolled over 4,100 students in 2024, a third consecutive record year.',
    focus: 'Private university',
    founded: '1968',
    source: 'https://www.pba.edu/news/palm-beach-atlantic-university-celebrates-third-consecutive-year-of-record-breaking-enrollment/',
  },
  {
    rank: 87,
    name: 'Community Foundation for Palm Beach and Martin Counties',
    city: 'West Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Community foundation managing donor funds and regional grantmaking.',
    why: 'Founded in 1972, it manages roughly $170 million in assets and has distributed over $150 million in grants.',
    focus: 'Community foundation',
    founded: '1972',
    source: 'https://yourcommunityfoundation.org/financials/',
  },
  {
    rank: 88,
    name: 'Quantum Foundation',
    city: 'West Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Private foundation funding safety-net healthcare and health education access countywide.',
    why: 'Formed in 1995 from $125 million in hospital sale proceeds and has since awarded $175 million in county grants.',
    focus: 'Health philanthropy',
    founded: '1995',
    source: 'https://quantumfnd.org/about-us/',
  },
  {
    rank: 89,
    name: 'Cultural Council for Palm Beach County',
    city: 'Lake Worth Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Umbrella nonprofit promoting and funding arts, culture and creative professionals countywide.',
    why: 'Founded in 1978 by Alexander W. Dreyfoos Jr., it serves as the county’s designated arts agency.',
    focus: 'Arts service organization',
    founded: '1978',
    source: 'https://www.palmbeachculture.com/about/our-history/',
  },
  {
    rank: 90,
    name: 'Business Development Board of Palm Beach County',
    city: 'West Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'The county’s official public-private economic development and business recruitment organization.',
    why: 'Founded in 1982, it is the designated body behind the corporate relocations reshaping the regional economy.',
    focus: 'Economic development',
    founded: '1982',
    source: 'https://bdb.org/about/',
  },
  {
    rank: 91,
    name: 'Preservation Foundation of Palm Beach',
    city: 'Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Nonprofit dedicated to preserving Palm Beach’s historic architecture and cultural heritage.',
    why: 'Incorporated in 1980, it has advocated for the designation of more than 300 local historic landmarks.',
    focus: 'Historic preservation',
    founded: '1980',
    source: 'https://www.palmbeachpreservation.org/history/',
  },
  {
    rank: 92,
    name: 'Palm Beach Zoo & Conservation Society',
    city: 'West Palm Beach',
    category: 'Philanthropy & Civic Institutions',
    description: 'Accredited zoo and conservation organization on 23 acres at Dreher Park.',
    why: 'Founded in 1969, it houses more than 350 animals and draws roughly 380,000 visitors a year.',
    focus: 'Zoo and conservation',
    founded: '1969',
    source: 'https://www.palmbeachzoo.org/zoo-history',
  },

  // ─── Emerging Growth Businesses ────────────────────────────────────────────
  {
    rank: 93,
    name: 'ModMed',
    city: 'Boca Raton',
    category: 'Emerging Growth Businesses',
    description: 'Develops AI-powered electronic health record and practice-management software for specialty practices.',
    why: 'Clearlake Capital acquired a majority stake from Warburg Pincus in March 2025 at a $5.3 billion valuation.',
    focus: 'Healthcare SaaS',
    founded: '2010',
    source: 'https://www.axios.com/pro/health-tech-deals/2025/03/03/clearlake-buys-modmed-stake-from-warburg-valuing-company-at-53b',
  },
  {
    rank: 94,
    name: 'DigitalBridge Group',
    city: 'Boca Raton',
    category: 'Emerging Growth Businesses',
    description: 'Global alternative asset manager investing in data centers, towers and fiber infrastructure.',
    why: 'NYSE-listed with roughly $108 billion in assets under management and subject to a pending SoftBank acquisition agreement.',
    focus: 'Digital infrastructure',
    founded: '2009',
    source: 'https://www.stocktitan.net/overview/DBRG/',
  },
  {
    rank: 95,
    name: 'Dycom Industries',
    city: 'West Palm Beach',
    category: 'Emerging Growth Businesses',
    description: 'Publicly traded specialty contractor building and maintaining telecom and utility infrastructure.',
    why: 'Signed a 40,000-square-foot lease to relocate its corporate headquarters to 300 Banyan in downtown West Palm Beach.',
    focus: 'Telecom infrastructure',
    founded: '1969',
    source: 'https://rebusinessonline.com/dycom-industries-signs-40000-sf-office-lease-for-new-headquarters-at-300-banyan-in-west-palm-beach/',
  },
  {
    rank: 96,
    name: 'Sensus Healthcare',
    city: 'Boca Raton',
    category: 'Emerging Growth Businesses',
    description: 'Public medical device maker of superficial radiation therapy systems for skin cancer treatment.',
    why: 'NASDAQ-listed with full-year 2024 revenue of $41.8 million, up 71 percent year over year.',
    focus: 'Medical device manufacturing',
    founded: '2010',
    source: 'https://sensushealthcare.com/sensus-healthcare-reports-fourth-quarter-and-full-year-2024-financial-results/',
  },
  {
    rank: 97,
    name: 'Basis Industrial',
    city: 'Delray Beach',
    category: 'Emerging Growth Businesses',
    description: 'Vertically integrated platform acquiring small-bay industrial and self-storage properties.',
    why: 'Named to the South Florida Business Journal’s 2025 Fastest-Growing Companies list with 47 properties totalling 7.2 million square feet.',
    focus: 'Industrial real estate platform',
    founded: '2020',
    source: 'https://basisindustrial.com/south-florida-business-journal-names-basis-industrial-one-of-the-fastest-growing-companies-of-2025/',
  },
  {
    rank: 98,
    name: 'Boarderie',
    city: 'Riviera Beach',
    category: 'Emerging Growth Businesses',
    description: 'E-commerce brand shipping pre-assembled charcuterie and grazing boards nationwide.',
    why: 'Generated more than $70 million in lifetime revenue and set a Guinness World Record following a Shark Tank deal.',
    focus: 'E-commerce food brand',
    founded: '2020',
    source: 'https://bdb.org/news/news-3-companies-in-palm-beach-county/',
  },
  {
    rank: 99,
    name: 'Tint World',
    city: 'Boca Raton',
    category: 'Emerging Growth Businesses',
    description: 'Franchisor of automotive styling, window tint and vehicle customization service centers.',
    why: 'Ranked number 4,836 on the 2025 Inc. 5000 list, its tenth appearance on the ranking.',
    focus: 'Automotive franchise',
    founded: '1982',
    source: 'https://www.prnewswire.com/news-releases/tint-world-ranks-no-4-836-on-the-2025-inc-5000-list-of-americas-fastest-growing-private-companies-302527839.html',
  },
  {
    rank: 100,
    name: 'Agbara Engineering',
    city: 'West Palm Beach',
    category: 'Emerging Growth Businesses',
    description: 'Power delivery engineering firm providing utility and grid infrastructure design services.',
    why: 'Debuted on the 2025 Inc. 5000 list of fastest-growing private companies at number 3,170.',
    focus: 'Power delivery engineering',
    founded: '2019',
    source: 'https://www.morningstar.com/news/pr-newswire/20250929ph85546/agbara-engineering-named-to-inc-5000-list-of-americas-fastest-growing-private-companies',
  },
];
